### PR TITLE
added garden/plants image to More Projects section

### PR DESCRIPTION
**Pull request by yeqbfgxjiq**
more-projects-plants

<br>
Added an image in the "More Projects" section on the homepage. This is what it looks like. 
<br>

### CODE REVIEW

**Comment by lkngtn** [comment]
Im not sure I like having a large graphic above the `More projects` button. I think having just the button flows better after the project sections as it currently stands. If we wanted to list specific projects in a horizontal row with small icons and links that might make sense. 

We could think of structuring the main sections into more mission/vision related topics as opposed to specific projects. Then move the fundraising and licensing section bellow with just a simple graphic and link. We could use a flower image for each of these projects with a small title (Fundraising, Licensing, Redemptions, etc). Here is a nice icon pack that would look cohesive. https://www.flaticon.com/packs/flowers-2

What do you think?

**Comment by yeqbfgxjiq** [comment]
Yeah we could do that. Actually sounds like a great idea. That would make sense to update before we "launch" and start promoting the project and submit our Nest Grant. What do you see as the main mission/vision bullet points we would want to emphasize there?

**Comment by lkngtn** [comment]
Here is what I'm thinking:

- Tools
	- **Digital Cooperatives**
	- Decentralized ledgers have enabled new forms of coordination and collaboration. We are building applications which enable open source communities to better attract and reward project maintainers and contributors. 
- Licensing 
	- **Growing the commons**
	- We believe that finding sustainable funding sources for open source projects is critical to growing the open source commons. To that end we are advocating for a novel open source license which combines the best aspects of copyleft and permissive style open source licensing.
- Community Driven
	- **Contributing to 1Hive**
	- We are an open and transparent organization. This enables you to see and understand how we operate, and of course join the community and help us improve. Many of our projects, both technical and non-technical, have open bounties.

Projects:
- Apiary
- Commons License
- Redemptions
- Dandelion OrgKit (Partnership)
- Tulip OrgKit (Cooperative)

**Comment by lkngtn** [comment]
Started working on this in https://github.com/1Hive/website/tree/home-refactor

**Comment by yeqbfgxjiq** [comment]
Closing because #33 is more up to date

**Pull request closed without merging**
